from turtle import *
def drline(x1,y1,x2,y2):
    penup()
    goto(x1,y1)
    pendown()
    goto(x2,y2)
def drround(size,fillTF):
    pendown()
    if fillTF == True:
        begin_fill()
    setheading(180)
    circle(size,360)
    if fillTF == True:
        end_fill()
def drrect(l,w,fillTF):
    pendown()
    if fillTF == True:
        begin_fill()
    for i in range(2):
        fd(l)
        right(90)
        fd(w)
        right(90)
    left(90)
    if fillTF == True:
        end_fill()
def drhead():
    color('blue','blue')
    penup()
    goto(0,100)
    drround(75,True)
    color('white','white')
    penup()
    goto(0,72)
    drround(60,True)
def dreyes():
    color('black','white')
    penup()
    goto(-15,80)
    drround(17,True)
    penup()
    goto(19,80)
    drround(17,True)
    color('black','black')
    penup()
    goto(-8,70)
    drround(6,True)
    penup()
    goto(12,70)
    drround(6,True)
    color('white','white')
    penup()
    goto(-8,66)
    drround(2,True)
    penup()
    goto(12,66)
    drround(2,True)
def drnose():
    color('red','red')
    penup()
    goto(0,40)
    drround(7,True)
def drmout():
    color('black','black')
    penup()
    goto(-30,-20)
    pendown()
    setheading(-27)
    circle(70,55)
    penup()
    goto(0,26)
    pendown()
    goto(0,-25)
def drwhsk():
    color('black','black')
    drline(10,5,-40,5)
    drline(10,5,40,5)
    drline(-10,15,-40,20)
    drline(10,15,40,20)
    drline(-10,-5,-40,-10)
    drline(10,-5,40,-10)
def drbody():
    color('blue','blue')
    penup()
    goto(0,-35)
    drround(80,True)
    color('white','white')
    goto(0,-35)
    drround(70,True)
    penup()
    goto(40,-45)
    color('red','red')
    drrect(80,10,True)
    color('black','black')
    penup()
    goto(-50,-110)
    pendown()
    setheading(-90)
    circle(50,180)
    goto(-55,-110)
    color('yellow','yellow')
    penup()
    goto(0,-41)
    drround(8,True)
    penup()
    goto(5,-47)
    color('black','black')
    drrect(10,4,False)
    penup()
    goto(0,-53)
    drround(2,True)
def drhand():
    #right
    penup()
    color('blue','blue')
    goto(-72,-90)
    pendown()
    begin_fill()
    goto(-150,-115)
    goto(-150,-87)
    goto(-58,-59)
    goto(-72,-90)
    end_fill()
    penup()
    goto(-160,-80)
    color('white','white')
    drround(25,True)
    #right
    penup()
    color('blue','blue')
    goto(72,-90)
    pendown()
    begin_fill()
    goto(150,-115)
    goto(150,-87)
    goto(58,-59)
    goto(72,-90)
    end_fill()
    penup()
    goto(160,-80)
    color('white','white')
    drround(25,True)
def drfeet():
    penup()
    goto(-20,-192)
    color('blue','blue')
    pendown()
    begin_fill()
    goto(-20,-275)
    goto(-55,-275)
    goto(-55,-170)
    goto(-20,-192)
    end_fill()
    penup()
    color('white','white')
    goto(-37.5,-250)
    drround(25,True)
    penup()
    goto(20,-192)
    color('blue','blue')
    pendown()
    begin_fill()
    goto(20,-275)
    goto(55,-275)
    goto(55,-170)
    goto(20,-192)
    end_fill()
    penup()
    color('white','white')
    goto(37.5,-250)
    drround(25,True)
screen = setup(1280,700)
title('doramon')
bgcolor('lightgrey')
speed('fastest')
drhead()
dreyes()
drnose()
drmout()
drwhsk()
drbody()
drhand()
drfeet()
mainloop()
